plugins {
	id 'java'
	id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}

repositories {
	maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

    runtimeOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    runtimeOnly "maven.modrinth:sodium:${project.sodium_version}-fabric"
    runtimeOnly "maven.modrinth:iris:${project.iris_version}-fabric"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            runDir = "../run"
            ideConfigGenerated = true
            client()
        }
    }
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)

    def props = [version: project.mod_version]
    inputs.properties(props)

    filesMatching("fabric.mod.json") {
        expand "version": project.mod_version
    }
}

tasks.named("check") {
    dependsOn "validateAccessWidener"
}
