plugins {
	id 'java'
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
        }
        maven {
            name = "ParchmentMC"
            url = "https://maven.parchmentmc.org/"
        }
        maven { url "https://maven.shedaniel.me/" }
    }

    if (name == "common") return

    configurations {
        commonJava {
            canBeResolved = true
        }
        commonResources {
            canBeResolved = true
        }
    }

    dependencies {
        compileOnly project(':common')
        commonJava project(path: ':common', configuration: 'commonJava')
        commonResources project(path: ':common', configuration: 'commonResources')
    }

    tasks.named('compileJava', JavaCompile) {
        dependsOn(configurations.commonJava)
        source(configurations.commonJava)
    }
}

jar {
    dependsOn subprojects.collect {
        it.tasks.named('build')
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    subprojects.each {
        from(it.tasks.named('jar', Jar).flatMap { it.archiveFile }.map { zipTree(it.asFile) }) {
            exclude 'META-INF/MANIFEST.MF'
        }
    }

    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.archives_base_name}" }
    }
}

base {
    archivesName = "${project.archives_base_name}-${project.mod_version}-${project.minecraft_version}"
}