# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1.1

# https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_loom_version=1.15-SNAPSHOT

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.1-1
# https://neoforged.net/
neoforge_loader_version=26.1.1.1-beta
# https://projects.neoforged.net/neoforged/ModDevGradle
neoforge_gradle_version=2.0.141

# Mod Properties
mod_version = 1.5.4
mod_id = mobhealthindicators
archives_base_name = MobHealthIndicators

# Dependencies
modmenu_version=18.0.0-alpha.8
cloth_config_version=26.1.154
sodium_version=mc26.1.1-0.8.9
iris_version=1.10.9+26.1
