# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G

minecraft_version=26.2

# https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_loom_version=1.17.14
fabric_api_version=0.154.2+26.2

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
# https://neoforged.net/
neoforge_loader_version=26.2.0.15-beta
# https://plugins.gradle.org/plugin/net.neoforged.moddev
neoforge_gradle_version=2.0.141

# Mod Properties
mod_version=1.5.5
mod_id=mobhealthindicators
archives_base_name=MobHealthIndicators

# Dependencies
modmenu_version=20.0.0
cloth_config_version=26.2.155
sodium_version=mc26.2-0.9.1
iris_version=1.11.2+26.2
